= kapture / datasets
:sectnums:
:sectnumlevels: 1
:toc:
:toclevels: 1

This section explains how to convert datasets to kapture format.

== 7-scenes

TODO: A word about the choices we made.

=== convert from original dataset

=== download precomputed kapture data

== Aachen-Day-Night-v1.1

TODO: A word about the choices we made.

=== convert from original dataset

=== download precomputed kapture data

== baidu

TODO: A word about the choices we made.

=== convert from original dataset

=== download precomputed kapture data

== Cambridge_Landmarks

TODO: A word about the choices we made.

=== convert from original dataset

== Extended-CMU-Seasons

We imported the poses from the text files. The same sliced structure is replicated.
In the precomputed kapture data, we decided to import all images, even if they are not listed in the text files (they do not have a pose).
In kapture_import_Extended_CMU_Seasons.py, it corresponds to the option --all-files.

=== convert from original dataset

Extended-CMU-Seasons is available here: https://data.ciirc.cvut.cz/public/projects/2020VisualLocalization/Extended-CMU-Seasons/

Once downloaded, and all tar files extracted, your Extended-CMU-Seasons directory is like this:

[source,txt]
----
Extended-CMU-Seasons
├─ README_Extended-CMU-Seasons.md
├─ export_sift_features.py
├─ intrinsics.txt
├─ slice2/
│  ├─ camera-poses/
│  │  ├─ slice-2-gt-query-images-20100901.txt
│  │  ├─ ...
│  ├─ database/
│  │  ├─ img_00119_c0_1303398474779439us.jpg
│  │  ├─ ...
│  ├─ database2.db
│  ├─ ground-truth-database-images-slice2.txt
│  ├─ query/
│  │  ├─ img_00273_c1_1287503834101037us.jpg
│  │  ├─ ...
│  ├─ query2.db
│  ├─ sparse/
│  │  ├─ cameras.bin
│  │  ├─ images.bin
│  │  └─ points3D.bin
│  └─ test-images-slice2.txt
├─ slice2/
├─ slice3/
├─ ...
└─ slice25/
----

To import Extended-CMU-Seasons to kapture, run:
[source,bash]
----
# note: on windows, this require admin rights for symlinks
# see https://docs.python.org/3.6/library/os.html#os.symlink
kapture_import_Extended_CMU_Seasons.py -v info -i ./Extended-CMU-Seasons/ -o ./kapture/Extended-CMU-Seasons/ --image_transfer link_absolute --all-files

# if you can't use symlinks, run
kapture_import_Extended_CMU_Seasons.py -v info -i ./Extended-CMU-Seasons/ -o ./kapture/Extended-CMU-Seasons/ --image_transfer copy --all-files
----

=== download precomputed kapture data

== InLoc

TODO: A word about the choices we made.

=== download precomputed kapture data

== RobotCar_Seasons-v2

TODO: A word about the choices we made.

=== convert from original dataset

=== download precomputed kapture data

== SILDa

1) download the original dataset

The authors provide a bash script `download.sh` to download all the available data for SILDa.
See the https://github.com/abmmusa/silda for more details.

[source,bash]
----
cd /your/working/dataset/directory  # replace the path
curl -L https://github.com/abmmusa/silda/raw/master/download.sh -o download.sh
chmod +x download.sh
./download.sh  # <  total of around 60GB data will be downloaded
----

or you can download only data relevant to kapture, applying the following command in bash terminal:

[source,bash]
----
mkdir -p ./data/SILDa
# Downloading full spherical images
wget -O im1 -L https://imperialcollegelondon.box.com/shared/static/ce2kkt0j4uir9tpzcxx55lhfr05bbjx9
wget -O im2 -L https://imperialcollegelondon.box.com/shared/static/j4rx03ymwajz98wsfgbocrurwjq4l68h
tar xvzf silda-images.tgz
mv silda-images ./data/SILDa/
rm im1 im2 silda-images.tgz

# Downloading camera intrinsics
wget -O camera-intrinsics.tar.xz -L https://imperialcollegelondon.box.com/shared/static/pug92l2sw2n375eqrqo92j63p5qm5dqo.xz
tar xf camera-intrinsics.tar.xz
mv camera-intrinsics ./data/SILDa/
rm camera-intrinsics.tar.xz

# Download camera poses for the train images
wget -O silda-train-poses.txt -L https://imperialcollegelondon.box.com/shared/static/jr67j3uw8sz97j4vw8la3j3vbhzfwpnz.txt
mv silda-train-poses.txt ./data/SILDa/
----

You should end up with

----
./data/SILDa/
├── camera-intrinsics
├── query_imgs.txt
├── silda-images
├── silda-train-poses.txt
├── train_imgs.txt
└── ...
----

2) import into kapture format

[source,bash]
----
# mapping part
kapture_import_silda.py -v info --corpus train -i ./data/SILDa -o ./kapture/SILDa/mapping --image_transfer copy
# query part
kapture_import_silda.py -v info --corpus query -i ./data/SILDa -o ./kapture/SILDa/query --image_transfer copy
# then [optionally] clean original
rm -rf ./data/SILDa
----

You should end up with

----
./kapture
└── SILDa
    ├── mapping
    │   └── sensors
    │       ├── records_camera.txt
    │       ├── records_data
    │       ├── rigs.txt
    │       ├── sensors.txt
    │       └── trajectories.txt
    └── query
        └── sensors
            ├── records_camera.txt
            ├── records_data
            ├── rigs.txt
            ├── sensors.txt
            └── trajectories.txt
----
